"""Recompute corrected battery evidence with paired seeds and explicit metrics.

Intervals describe initialization variability on one fixed cell split. They do
not quantify uncertainty over new train/test cell partitions or populations.
"""
import argparse
import hashlib
import json
from pathlib import Path
import numpy as np
from paired_stats import wilcoxon_exact


def summarize(values):
    x=np.asarray(values,dtype=float)
    return dict(mean=float(x.mean()),std_population=float(x.std()),n=len(x))


def paired(a,b):
    d=np.asarray(a)-np.asarray(b)
    assert len(d)==10
    half=2.2621571628*d.std(ddof=1)/np.sqrt(len(d))
    p,_=wilcoxon_exact(d.tolist())
    return dict(mean_difference=float(d.mean()),ci95_t=[float(d.mean()-half),float(d.mean()+half)],
                improved_seeds=int((d<0).sum()),p_wilcoxon=p)


def main():
    ap=argparse.ArgumentParser();ap.add_argument('--root',default=str(Path(__file__).resolve().parents[2]))
    a=ap.parse_args();root=Path(a.root);result={}
    for dataset in ('MATR','NASA'):
        path=root/'results/BAT_VALIDATION_V2'/f'{dataset}_10s150.json'
        blob=path.read_bytes();d=json.loads(blob)
        assert d['complete'] and len(d['rows'])==50
        cells=d['metadata']['cells'];sets={k:set(v) for k,v in cells.items()}
        assert not(sets['train']&sets['validation'] or sets['train']&sets['test'] or sets['validation']&sets['test'])
        modes={mode:sorted([r for r in d['rows'] if r['mode']==mode],key=lambda r:r['seed']) for mode in ('single_soh','joint','stf0','stfcal','stfcalrank')}
        assert all([r['seed'] for r in rows]==list(range(10)) for rows in modes.values())
        anchors={r['seed']:r['representation']['between_sample_trace'] for r in modes['single_soh']}
        rows={}
        for mode,rs in modes.items():
            rows[mode]={metric:summarize([r['test'][metric] for r in rs]) for metric in ('soh_rmse','rul_observed_mae')}
            if rs[0]['test']['n_censored']:
                rows[mode]['rul_censored_shortfall']=summarize([r['test']['rul_censored_shortfall'] for r in rs])
            for metric in ('between_sample_trace','participation_rank','entropy_rank'):
                rows[mode][metric]=summarize([r['representation'][metric] for r in rs])
            rows[mode]['relative_trace']=summarize([r['representation']['between_sample_trace']/anchors[r['seed']] for r in rs])
            rows[mode]['soh_prediction_variance']=summarize([r['representation']['prediction_variance_normalized_units'][0]*10000 for r in rs])
            rows[mode]['legacy_validation_coordinate_variance']=summarize([r['validation']['scatter'] for r in rs])
        comparisons={}
        for mode in ('stf0','stfcal','stfcalrank'):
            comparisons[mode]={metric:paired([r['test'][metric] for r in modes[mode]],[r['test'][metric] for r in modes['joint']]) for metric in ('soh_rmse','rul_observed_mae')}
        result[dataset]=dict(source=str(path.relative_to(root)),sha256=hashlib.sha256(blob).hexdigest(),
            cell_counts={k:len(v) for k,v in sets.items()},sample_counts=d['metadata']['sample_counts'],
            n_observed_test=d['rows'][0]['test']['n_observed'],n_censored_test=d['rows'][0]['test']['n_censored'],
            rows=rows,comparisons= comparisons,scope='ten initialization seeds; one fixed cell split')
        print(dataset,'cells',result[dataset]['cell_counts'])
        for mode,row in rows.items():
            print(mode,{k:round(v['mean'],5) for k,v in row.items()})
        print('PAIRED',comparisons)
    out=root/'results/OPERATOR_AUDIT/current_battery_evidence.json'
    out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(result,indent=2),newline='\n')
    tex=[r'% Generated by repro/scripts/current_evidence_audit.py; do not edit numbers.',
         r'\begin{table}[t]\centering\footnotesize',
         r'\caption{Corrected battery test results. Means $\pm$ population standard deviations over ten initialization seeds on one fixed cell split. RUL is observed-only MAE; $S$ is across-example covariance trace, PR is participation rank, and $V_{\mathrm{pred}}$ is SOH prediction variance in squared percentage points. The SOH-only head does not train RUL.}',
         r'\label{tab:battery_evidence}',
         r'\resizebox{\columnwidth}{!}{\begin{tabular}{llrrrrr}\toprule',
         r'Data & Mode & SOH RMSE (\%) & RUL MAE & $S$ & PR & $V_{\mathrm{pred}}$ \\',r'\midrule']
    labels=dict(single_soh='SOH-only',joint=r'\textsc{joint}',stf0=r'\textsc{stf-0}',stfcal=r'\textsc{stfcal}',stfcalrank=r'\textsc{stfcalrank}')
    for dataset,d in result.items():
        for mode,row in d['rows'].items():
            values=[]
            for metric in ('soh_rmse','rul_observed_mae','between_sample_trace','participation_rank','soh_prediction_variance'):
                v=row[metric]
                values.append('---' if mode=='single_soh' and metric=='rul_observed_mae' else f"${v['mean']:.2f}\\pm{v['std_population']:.2f}$")
            tex.append(' & '.join([dataset,labels[mode]]+values)+r' \\')
        tex.append(r'\midrule')
    tex[-1]=r'\bottomrule\end{tabular}}\end{table}'
    (root/'paper/battery_evidence_table.tex').write_text('\n'.join(tex)+'\n',newline='\n')


if __name__=='__main__':main()
