"""Distinguish nominal rank from deletion when the calibrated gate is open."""
import hashlib
import json
from pathlib import Path
import numpy as np


def main():
    root=Path(__file__).resolve().parents[2]
    rows=[]
    for alpha in (12,30,100):
        paired={}
        for basis in ('pca','aux'):
            path=root/'results/XDRBASIS_REAL'/f'har_recon_a{alpha}.0_{basis}_r64.json'
            blob=path.read_bytes();d=json.loads(blob)
            rs=sorted([r for r in d['raw'] if r['mode']=='stfcalrank'],key=lambda r:r['seed'])
            assert [r['seed'] for r in rs]==list(range(10))
            active=[r for r in rs if r['gate']>0]
            row=dict(alpha=alpha,basis=basis,n=10,active_seeds=[r['seed'] for r in active],
                     nominal_rank=float(np.mean([r['rank'] for r in rs])),
                     active_rank=float(np.mean([r['rank'] for r in active])),
                     gate_weighted_rank=float(np.mean([r['rank']*r['gate'] for r in rs])),
                     accuracy=float(np.mean([r['metric'] for r in rs])),
                     accuracy_std=float(np.std([r['metric'] for r in rs])),
                     relative_scatter=float(np.mean([r['rel_scatter'] for r in rs])),
                     source=str(path.relative_to(root)),sha256=hashlib.sha256(blob).hexdigest())
            rows.append(row);paired[basis]=row
        assert paired['pca']['active_seeds']==paired['aux']['active_seeds']
    out=root/'results/OPERATOR_AUDIT/real_basis_evidence.json'
    out.write_text(json.dumps(dict(scope='Candidate ranks include closed-gate seeds; active rank conditions on gate=1. Gate-weighted rank excludes warm-up duration.',rows=rows),indent=2),newline='\n')
    tex=[r'% Generated by repro/scripts/real_basis_evidence_audit.py',r'\begin{table}[t]\centering\small',
         r'\caption{Real HAR reconstruction ($m=R=64$, ten seeds). Candidate ranks include closed-gate seeds; active ranks average only gate-open seeds. Accuracy and scatter average all ten seeds. PCA and auxiliary-gradient bases activate on identical seeds; these results establish neither superiority over joint training nor globally optimal deletion.}',
         r'\label{tab:realbasis}',r'\resizebox{\columnwidth}{!}{\begin{tabular}{clrrrrr}\toprule',
         r'$\alpha$ & basis & gate open & candidate rank & active rank & rel.\ scatter & accuracy \\',r'\midrule']
    basis_label={'pca':'PCA','aux':'Aux. grad.'}
    for r in rows:
        tex.append(f"${r['alpha']}$ & {basis_label[r['basis']]} & ${len(r['active_seeds'])}/10$ & ${r['nominal_rank']:.1f}$ & ${r['active_rank']:.2f}$ & ${r['relative_scatter']:.3f}$ & ${r['accuracy']:.4f}$"+r' \\')
    tex.append(r'\bottomrule\end{tabular}}\end{table}')
    (root/'paper/real_basis_evidence_table.tex').write_text('\n'.join(tex)+'\n',newline='\n')
    print(json.dumps(rows,indent=2))


if __name__=='__main__':main()
