"""Aggregate multi-seed STF ablation into a paper LaTeX table with mean +/- std.

Reads wf_stf_ablation_multiseed.json (cell-level means/std over seeds) and emits
  ../results/wf_stf_ablation_multiseed.tex
  ../results/wf_stf_ablation_multiseed_latex.md
The table mirrors wf_stf_summary.py's format (val-IC / aux per toxicity x mode)
but reports mean +/- std instead of bare means.

Usage:
  python wf_stf_summary_multi.py <path-to-multiseed.json> [--out <tex>]
"""
from __future__ import annotations

import argparse
import json
import os

MODE_ORDER = ["off", "stf0", "hard", "soft"]
TOXIC_ORDER = ["rank_only", "rank_w1_k8", "rank_w5_k16", "rank_w20_k64", "rank_w100_k64"]
TOXIC_W = {"rank_only": 0, "rank_w1_k8": 1, "rank_w5_k16": 5,
           "rank_w20_k64": 20, "rank_w100_k64": 100}


def _fmt(m, s, digits=3):
    return "{:+.{d}f}$\\pm${s:.{d}f}".format(m, s=s, d=digits)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("json", nargs="?", default=os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "results",
        "wf_stf_ablation_multiseed.json"))
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    with open(args.json) as f:
        data = json.load(f)
    cells = {c["toxic"] + "/" + c["stf_mode"]: c for c in data["cells"]}
    seeds = data.get("seeds", "?")

    lines = ["% STF ablation (multi-seed) -- auto-generated by wf_stf_summary_multi.py",
             r"\begin{table}[t]",
             r"\centering",
             r"\caption{Spectral Toxicity Filtering (multi-seed, "
             f"${seeds}$ seeds, mean$\\pm$std). "
             r"\emph{soft} recovers primary-task validation Rank-IC under "
             r"auxiliary-toxicity collapse while preserving auxiliary fit "
             r"(low aux) far better than the blunt full-detach \emph{STF-0}; "
             r"under extreme toxicity the single-subspace filter saturates and "
             r"full detach is the fallback.}",
             r"\label{tab:stf_ablation_multi}",
             r"\small",
             r"\resizebox{\columnwidth}{!}{\begin{tabular}{lcccccccc}",
             r"\toprule",
             r"\textbf{$w_{\mathrm{aux}}$} & \multicolumn{2}{c}{\textbf{off}} & "
             r"\multicolumn{2}{c}{\textbf{STF-0}} & \multicolumn{2}{c}{\textbf{hard}} & "
             r"\multicolumn{2}{c}{\textbf{soft}} \\",
             r" & val-IC & aux & val-IC & aux & val-IC & aux & val-IC & aux \\\midrule"]
    for toxic in TOXIC_ORDER:
        row = [str(TOXIC_W[toxic])]
        for mode in MODE_ORDER:
            c = cells.get(f"{toxic}/{mode}")
            row.append(_fmt(c["val_ic_mean"], c["val_ic_std"]) if c else "--")
            row.append(_fmt(c["aux_val_mean"], c["aux_val_std"]) if c else "--")
        lines.append(" & ".join(row) + r" \\")
    lines += [r"\midrule", r"\end{tabular}}", r"\end{table}"]

    out = args.out or args.json.replace(".json", ".tex")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[saved] {out}")

    # markdown view
    md_lines = ["| $w_{aux}$ | off val-IC | off aux | STF-0 val-IC | STF-0 aux | "
                "hard val-IC | hard aux | soft val-IC | soft aux |",
                "|---|---|---|---|---|---|---|---|---|"]
    for toxic in TOXIC_ORDER:
        parts = [str(TOXIC_W[toxic])]
        for mode in MODE_ORDER:
            c = cells.get(f"{toxic}/{mode}")
            parts.append(f"{c['val_ic_mean']:+.3f}±{c['val_ic_std']:.3f}" if c else "--")
            parts.append(f"{c['aux_val_mean']:.3f}±{c['aux_val_std']:.3f}" if c else "--")
        md_lines.append("| " + " | ".join(parts) + " |")
    md_path = out.replace(".tex", "_latex.md")
    with open(md_path, "w") as f:
        f.write("\n".join(md_lines) + "\n")
    print(f"[saved] {md_path}")


if __name__ == "__main__":
    main()