"""Summarise wf_stf_ablation.json into a paper-ready LaTeX table + a compact CSV.

Groups by toxic config and arranges STF modes (off/stf0/hard/soft) in columns for
val_ic / oos_ic / sigma_h / aux_val, so the reviewer sees at a glance that STF
recovers the primary IC under toxicity while preserving aux-task fit (aux_val stays
close to 'off', unlike full-detach stf0).
"""
from __future__ import annotations
import csv
import json
import os

RES = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "results", "wf_stf_ablation.json")
MODE_ORDER = ["off", "stf0", "hard", "soft"]
KEYS = ["val_ic", "oos_ic", "collapse", "aux_val"]

with open(RES) as f:
    rows = json.load(f)

by_toxic: dict = {}
for r in rows:
    by_toxic.setdefault(r["toxic"], {})[r["stf_mode"]] = r

# CSV
csv_out = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "..", "results", "wf_stf_ablation_summary.csv")
with open(csv_out, "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["toxic", "stf_mode", "val_ic", "oos_ic", "collapse", "aux_val",
                "sigma_h", "stf_rho", "stf_w"])
    for toxic in ["rank_only", "rank_w1_k8", "rank_w5_k16", "rank_w20_k64", "rank_w100_k64"]:
        for m in MODE_ORDER:
            r = by_toxic.get(toxic, {}).get(m)
            if r is None:
                continue
            w.writerow([toxic, m, r["val_ic"], r["oos_ic"], r["collapse"],
                        r["aux_val"], r["sigma_h"], r["stf_rho"], r["stf_w"]])
print("[csv] wrote", csv_out)

# LaTeX table
lines = []
lines.append("% STF ablation -- auto-generated by wf_stf_summary.py")
lines.append(r"\begin{table}[t]")
lines.append(r"\centering")
lines.append(r"\caption{Spectral Toxicity Filtering recovers primary-task Rank-IC "
             r"under auxiliary-toxicity collapse while keeping auxiliary fit almost "
             r"intact. Toxicity $w_{\mathrm{aux}}$ is the weight of a variance-"
             r"shrinking fixed-projection aux head. \emph{soft} consistently beats "
             r"\emph{off} (collapse) and the blunt full-detach \emph{STF-0} on "
             r"val-IC, while its aux stays far closer to healthy \emph{off} than "
             r"STF-0 (lower aux = better-served auxiliary tasks). Under extreme "
             r"toxicity ($w_{\mathrm{aux}}\geq20$) the toxic push saturates in all "
             r"projection directions, so the single-subspace linear filter is "
             r"overwhelmed and full detach becomes the fallback. val-IC is the "
             r"out-of-train validation Rank-IC (early-stopping selection metric); "
             r"the encoder-scatter collapse indicator is reported in text.}")
lines.append(r"\label{tab:stf_ablation}")
lines.append(r"\small")
lines.append(r"\begin{tabular}{l" + "cccccccc" + "}")
lines.append(r"\toprule")
lines.append(r"\textbf{$w_{\mathrm{aux}}$} & \multicolumn{2}{c}{\textbf{off}} & "
             r"\multicolumn{2}{c}{\textbf{STF-0}} & \multicolumn{2}{c}{\textbf{hard}} & "
             r"\multicolumn{2}{c}{\textbf{soft}} \\")
lines.append(r" & val-IC & aux & val-IC & aux "
             r"& val-IC & aux & val-IC & aux \\"
             r"\midrule")
for toxic, waux in [("rank_only", "0"), ("rank_w1_k8", "1"),
                    ("rank_w5_k16", "5"), ("rank_w20_k64", "20")]:
    cells = [waux]
    for m in MODE_ORDER:
        r = by_toxic.get(toxic, {}).get(m)
        if r is None:
            cells += ["--", "--"]
        else:
            cells += [f"{r['val_ic']:+.3f}", f"{r['aux_val']:.3f}"]
    lines.append(" & ".join(cells) + r" \\")
lines.append(r"\midrule")
lines.append(r"\end{tabular}")
lines.append(r"\end{table}")
lines.append("")
tex_out = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "..", "results", "wf_stf_ablation_table.tex")
with open(tex_out, "w") as f:
    f.write("\n".join(lines))
print("[tex] wrote", tex_out)

# console summary
print()
for toxic in ["rank_only", "rank_w1_k8", "rank_w5_k16", "rank_w20_k64", "rank_w100_k64"]:
    print(f"--- {toxic} ---")
    for m in MODE_ORDER:
        r = by_toxic.get(toxic, {}).get(m)
        if r is None:
            continue
        print(f"  {m:5s} val_ic={r['val_ic']:+.4f} oos_ic={r['oos_ic']:+.4f} "
              f"collapse={r['collapse']:.4f} aux_val={r['aux_val']:.4f}")